imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale: %locale%
    session:
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: "C:\Program Files (x86)\Java\jre6\bin\java.exe"
    filters:
        cssrewrite: ~
        cssembed:
            jar: "%kernel.root_dir%/Resources/java/cssembed-0.3.6.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
        less:
            node: [C:\Program Files (x86)\nodejs\node.exe]
            node_paths: [C:\Program Files (x86)\nodejs\node_modules]

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

# Propel
propel:
    path:       "%kernel.root_dir%/../vendor/propel/propel1"
    phing_path: "%kernel.root_dir%/../vendor/pear-phing"
#    logging:   %kernel.debug%
#    build_properties:
#        xxxxx.xxxxx: xxxxxx
#        xxxxx.xxxxx: xxxxxx

fos_user:
    db_driver: 'propel'
    firewall_name: main
    user_class: FOS\UserBundle\Propel\UserProxy
    propel_user_class: Pixel\UserBundle\Model\User
    profile:
      form:
        type: pixel_user_profile
