parameters:
  database_driver:   mysql
  database_host:     localhost
  database_port:     ~
  database_name:     sf2_tests
  database_user:     root
  database_password: ~

  mailer_transport:  smtp
  mailer_host:       localhost
  mailer_user:       ~
  mailer_password:   ~

  locale:            en
  secret:            6c0896b211a37ff876085e1025edc7a5e95fbf8b
